import type { NotebookCell } from "../../runtime";

export function createDemoCells(): NotebookCell[] {
  return [
    {
      id: "spotify-1",
      cell_type: "markdown",
      source: [
        "# Spotify Tracks Analysis\n",
        "\n",
        "Exploring **1 million Spotify tracks** with audio features, popularity scores, and genre classifications.\n",
        "\n",
        "Dataset: [Spotify 1 Million Tracks](https://www.kaggle.com/datasets/amitanshjoshi/spotify-1million-tracks) (Kaggle)",
      ],
      metadata: {},
    },
    {
      id: "spotify-2",
      cell_type: "markdown",
      source: ["## Explore the Data"],
      metadata: {},
    },
    {
      id: "spotify-3",
      cell_type: "code",
      source: ["%sql\n", "SELECT * FROM '/mnt/local/spotify_data.parquet'"],
      outputs: [],
      execution_count: null,
      metadata: {
        viewName: "tracks",
        activeTab: "results",
        visibleRows: 3,
        assertConfig: { tests: [] },
      },
    },
    {
      id: "7jtyai1",
      cell_type: "markdown",
      source: ["## Average Track Duration Over Time"],
      metadata: {},
    },
    {
      id: "spotify-20",
      cell_type: "code",
      source: [
        "%sql\n",
        "SELECT\n",
        "  year,\n",
        "  round(avg(duration_ms) / 1000, 1) AS avg_duration_sec,\n",
        "  count(*) AS track_count\n",
        "FROM tracks\n",
        "WHERE year >= 2000\n",
        "GROUP BY year\n",
        "ORDER BY year",
      ],
      outputs: [
        {
          output_type: "execute_result",
          data: {
            "application/json": [
              { year: 2000, avg_duration_sec: 259.9, track_count: 44034 },
              { year: 2001, avg_duration_sec: 261.9, track_count: 42351 },
              { year: 2002, avg_duration_sec: 263.3, track_count: 42102 },
              { year: 2003, avg_duration_sec: 259, track_count: 42368 },
              { year: 2004, avg_duration_sec: 258.4, track_count: 43390 },
              { year: 2005, avg_duration_sec: 261.7, track_count: 43780 },
              { year: 2006, avg_duration_sec: 263.2, track_count: 45474 },
              { year: 2007, avg_duration_sec: 264.9, track_count: 46001 },
              { year: 2008, avg_duration_sec: 263.9, track_count: 47432 },
              { year: 2009, avg_duration_sec: 265.6, track_count: 46869 },
              { year: 2010, avg_duration_sec: 267, track_count: 46868 },
              { year: 2011, avg_duration_sec: 258.3, track_count: 46444 },
              { year: 2012, avg_duration_sec: 258, track_count: 54797 },
              { year: 2013, avg_duration_sec: 256.9, track_count: 53216 },
              { year: 2014, avg_duration_sec: 251.6, track_count: 53179 },
              { year: 2015, avg_duration_sec: 250.1, track_count: 51607 },
              { year: 2016, avg_duration_sec: 247.6, track_count: 40273 },
              { year: 2017, avg_duration_sec: 239.1, track_count: 56241 },
              { year: 2018, avg_duration_sec: 235.7, track_count: 56572 },
              { year: 2019, avg_duration_sec: 231, track_count: 55793 },
              { year: 2020, avg_duration_sec: 226.1, track_count: 55066 },
              { year: 2021, avg_duration_sec: 222.5, track_count: 53566 },
              { year: 2022, avg_duration_sec: 216.6, track_count: 53692 },
              { year: 2023, avg_duration_sec: 227.8, track_count: 38649 },
            ],
            "text/plain": ["Table with 3 columns, 24 rows"],
          },
          metadata: { totalRows: 24 },
          execution_count: 58,
        },
      ],
      execution_count: 58,
      metadata: {
        visualizeConfig: {
          chartType: "area",
          xColumn: "year",
          yColumns: ["avg_duration_sec"],
        },
        viewName: "duration_by_year",
        activeTab: "insights",
      },
    },
    {
      id: "spotify-4",
      cell_type: "code",
      source: [
        "%sql\n",
        "SELECT\n",
        "  count(*) AS total_tracks,\n",
        "  count(DISTINCT artist_name) AS unique_artists,\n",
        "  round(avg(popularity), 1) AS avg_popularity,\n",
        "  round(avg(danceability), 2) AS avg_danceability,\n",
        "  round(avg(energy), 2) AS avg_energy\n",
        "FROM tracks",
      ],
      outputs: [
        {
          output_type: "execute_result",
          data: {
            "application/json": [
              {
                total_tracks: 1159764,
                unique_artists: 64159,
                avg_popularity: 18.4,
                avg_danceability: 0.54,
                avg_energy: 0.64,
              },
            ],
            "text/plain": ["Table with 5 columns, 1 rows"],
          },
          metadata: { totalRows: 1 },
          execution_count: 61,
        },
      ],
      execution_count: 61,
      metadata: {
        viewName: "track_stats",
        activeTab: "results",
      },
    },
    {
      id: "spotify-5",
      cell_type: "markdown",
      source: ["## Popularity Distribution by Year"],
      metadata: {},
    },
    {
      id: "spotify-6",
      cell_type: "code",
      source: [
        "%sql\n",
        "SELECT\n",
        "  year,\n",
        "  count(*) AS track_count,\n",
        "  round(avg(popularity), 1) AS avg_popularity\n",
        "FROM tracks\n",
        "WHERE year >= 2000\n",
        "GROUP BY year\n",
        "ORDER BY year",
      ],
      outputs: [],
      execution_count: null,
      metadata: {
        viewName: "by_year",
        visualizeConfig: {
          chartType: "line",
          xColumn: "year",
          yColumns: ["avg_popularity"],
        },
      },
    },
    {
      id: "spotify-7",
      cell_type: "markdown",
      source: [
        "## What Makes a Track Popular?\n",
        "\n",
        "Let's look at the audio features that correlate with high popularity.",
      ],
      metadata: {},
    },
    {
      id: "spotify-8",
      cell_type: "code",
      source: [
        "import pandas as pd\n",
        "\n",
        "features = ['danceability', 'energy', 'loudness', 'speechiness',\n",
        "            'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo']\n",
        "\n",
        "corr = tracks[features + ['popularity']].corr()['popularity'].drop('popularity').sort_values(ascending=False)\n",
        "print('Correlation with popularity:\\n')\n",
        "for feat, val in corr.items():\n",
        "    bar = '+' * int(abs(val) * 40)\n",
        "    sign = '+' if val > 0 else '-'\n",
        "    print(f'  {feat:20s} {sign}{bar} ({val:+.3f})')",
      ],
      outputs: [],
      execution_count: null,
      metadata: {},
    },
    {
      id: "spotify-9",
      cell_type: "markdown",
      source: ["## Top Genres by Track Count"],
      metadata: {},
    },
    {
      id: "spotify-10",
      cell_type: "code",
      source: [
        "%sql\n",
        "SELECT\n",
        "  genre,\n",
        "  count(*) AS track_count,\n",
        "  round(avg(popularity), 1) AS avg_popularity\n",
        "FROM tracks\n",
        "GROUP BY genre\n",
        "ORDER BY track_count DESC\n",
        "LIMIT 15",
      ],
      outputs: [
        {
          output_type: "execute_result",
          data: {
            "application/json": [
              { genre: "black-metal", track_count: 985, avg_popularity: 11.4 },
              { genre: "ambient", track_count: 981, avg_popularity: 22.3 },
              { genre: "acoustic", track_count: 968, avg_popularity: 16.4 },
              { genre: "alt-rock", track_count: 954, avg_popularity: 37.6 },
              { genre: "afrobeat", track_count: 802, avg_popularity: 7.7 },
              { genre: "blues", track_count: 310, avg_popularity: 30.4 },
            ],
            "text/plain": ["Table with 3 columns, 6 rows"],
          },
          metadata: { totalRows: 6 },
          execution_count: 16,
        },
      ],
      execution_count: 16,
      metadata: {
        viewName: "top_genres",
        visualizeConfig: {
          chartType: "bar",
          xColumn: "genre",
          yColumns: ["track_count"],
        },
      },
    },
    {
      id: "spotify-11",
      cell_type: "markdown",
      source: [
        "## Most Popular Genres\n",
        "\n",
        "Sorted by average popularity instead of count:",
      ],
      metadata: {},
    },
    {
      id: "spotify-12",
      cell_type: "code",
      source: [
        "%sql\n",
        "SELECT\n",
        "  genre,\n",
        "  count(*) AS track_count,\n",
        "  round(avg(popularity), 1) AS avg_popularity\n",
        "FROM tracks\n",
        "GROUP BY genre\n",
        "HAVING count(*) > 1000\n",
        "ORDER BY avg_popularity DESC\n",
        "LIMIT 15",
      ],
      outputs: [
        {
          output_type: "execute_result",
          data: {
            "application/json": [
              { genre: "pop", track_count: 6235, avg_popularity: 55.7 },
              { genre: "hip-hop", track_count: 15703, avg_popularity: 46.3 },
              { genre: "rock", track_count: 3319, avg_popularity: 46.2 },
              { genre: "dance", track_count: 17212, avg_popularity: 43 },
              { genre: "metal", track_count: 7020, avg_popularity: 39.7 },
              { genre: "alt-rock", track_count: 20918, avg_popularity: 38.6 },
              { genre: "sad", track_count: 6086, avg_popularity: 36.1 },
              { genre: "indie-pop", track_count: 10022, avg_popularity: 35.5 },
              { genre: "folk", track_count: 16170, avg_popularity: 33.4 },
              { genre: "country", track_count: 17883, avg_popularity: 33 },
              { genre: "electro", track_count: 11406, avg_popularity: 31.5 },
              { genre: "punk", track_count: 6197, avg_popularity: 31.4 },
              { genre: "jazz", track_count: 15943, avg_popularity: 30.4 },
              { genre: "soul", track_count: 8974, avg_popularity: 30.4 },
              { genre: "k-pop", track_count: 20004, avg_popularity: 27.7 },
            ],
            "text/plain": ["Table with 3 columns, 15 rows"],
          },
          metadata: { totalRows: 15 },
          execution_count: 24,
        },
      ],
      execution_count: 24,
      metadata: {
        visualizeConfig: {
          chartType: "bar",
          xColumn: "genre",
          yColumns: ["avg_popularity"],
        },
        viewName: "popular_genres",
      },
    },
    {
      id: "spotify-13",
      cell_type: "markdown",
      source: [
        "## Energy vs Danceability\n",
        "\n",
        "A scatter plot of the two most common audio features:",
      ],
      metadata: {},
    },
    {
      id: "spotify-14",
      cell_type: "code",
      source: [
        "import matplotlib.pyplot as plt\n",
        "\n",
        "sample = tracks.sample(n=min(5000, len(tracks)), random_state=42)\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(6, 3))\n",
        "scatter = ax.scatter(\n",
        "    sample['energy'], sample['danceability'],\n",
        "    c=sample['popularity'], cmap='viridis',\n",
        "    alpha=0.4, s=8\n",
        ")\n",
        "plt.colorbar(scatter, label='Popularity')\n",
        "ax.set_xlabel('Energy')\n",
        "ax.set_ylabel('Danceability')\n",
        "ax.set_title('Energy vs Danceability (colored by popularity)')\n",
        "plt.tight_layout()\n",
        "plt.show()",
      ],
      outputs: [],
      execution_count: null,
      metadata: {},
    },
    {
      id: "spotify-15",
      cell_type: "markdown",
      source: [
        "## Audio Feature Profiles by Genre\n",
        "\n",
        "Compare how genres differ across key audio dimensions:",
      ],
      metadata: {},
    },
    {
      id: "spotify-16",
      cell_type: "code",
      source: [
        "top_5_genres = tracks.groupby('genre')['genre'].count().nlargest(5).index.tolist()\n",
        "subset = tracks[tracks['genre'].isin(top_5_genres)]\n",
        "\n",
        "features = ['danceability', 'energy', 'acousticness', 'valence', 'instrumentalness']\n",
        "profile = subset.groupby('genre')[features].mean()\n",
        "\n",
        "print('Average audio features by genre:\\n')\n",
        "print(profile.round(3).to_string())",
      ],
      outputs: [
        {
          output_type: "stream",
          name: "stdout",
          text: [
            "Average audio features by genre:\n",
            "\n",
            "             danceability  energy  acousticness  valence  instrumentalness\n",
            "genre                                                                     \n",
            "acoustic            0.532   0.481         0.487    0.418             0.108\n",
            "afrobeat            0.637   0.707         0.240    0.690             0.267\n",
            "alt-rock            0.505   0.756         0.116    0.458             0.061\n",
            "ambient             0.334   0.272         0.727    0.155             0.762\n",
            "black-metal         0.281   0.832         0.050    0.168             0.521",
          ],
        },
      ],
      execution_count: 19,
      metadata: {},
    },
    {
      id: "spotify-17",
      cell_type: "markdown",
      source: ["## Tempo Distribution"],
      metadata: {},
    },
    {
      id: "spotify-18",
      cell_type: "code",
      source: [
        "%sql\n",
        "SELECT\n",
        "  CASE\n",
        "    WHEN tempo < 80 THEN 'Slow (<80)'\n",
        "    WHEN tempo < 100 THEN 'Moderate (80-100)'\n",
        "    WHEN tempo < 120 THEN 'Upbeat (100-120)'\n",
        "    WHEN tempo < 140 THEN 'Fast (120-140)'\n",
        "    ELSE 'Very Fast (140+)'\n",
        "  END AS tempo_range,\n",
        "  count(*) AS track_count\n",
        "FROM tracks\n",
        "GROUP BY tempo_range\n",
        "ORDER BY track_count DESC",
      ],
      outputs: [
        {
          output_type: "execute_result",
          data: {
            "application/json": [
              { tempo_range: "Fast (120-140)", track_count: 331256 },
              { tempo_range: "Very Fast (140+)", track_count: 280081 },
              { tempo_range: "Upbeat (100-120)", track_count: 240656 },
              { tempo_range: "Moderate (80-100)", track_count: 220021 },
              { tempo_range: "Slow (<80)", track_count: 87750 },
            ],
            "text/plain": ["Table with 2 columns, 5 rows"],
          },
          metadata: { totalRows: 5 },
          execution_count: 57,
        },
      ],
      execution_count: 57,
      metadata: {
        visualizeConfig: {
          chartType: "pie",
          xColumn: "tempo_range",
          yColumns: ["track_count"],
        },
        viewName: "tempo_dist",
      },
    },
  ];
}
